openapi: "3.0.3"
info:
  title: "Documentación de la App de Reservas de Cabañas - Lodges"
  description: "API para la administración y consulta de cabañas disponibles para hospedaje en Las Trancas Lodges."
  version: "1.0.0"

servers:
  - url: http://localhost:8080

paths:

  /api/lodges:
    get:
      summary: Obtener lodges filtrados
      description: Devuelve una lista paginada de lodges con filtros opcionales.
      tags: [Lodges]
      parameters:
        - in: query
          name: hotel
          schema: { type: string }
        - in: query
          name: size
          schema: { type: integer }
        - in: query
          name: bedroom
          schema: { type: integer }
        - in: query
          name: bathroom
          schema: { type: integer }
        - in: query
          name: capacity
          schema: { type: integer }
        - in: query
          name: wifi
          schema: { type: string, enum: ["true", "false"] }
        - in: query
          name: available
          schema: { type: string, enum: ["true", "false"] }
        - in: query
          name: high
          schema: { type: number }
        - in: query
          name: medium
          schema: { type: number }
        - in: query
          name: low
          schema: { type: number }
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 10 }
      responses:
        '200': { description: Lista de lodges filtrada y paginada. }
        '500': { description: Error del servidor. }

    delete:
      summary: Eliminar todos los lodges
      tags: [Lodges]
      responses:
        '200': { description: Todos los lodges eliminados con éxito. }
        '500': { description: Error del servidor. }

  /api/lodges/{id}:
    get:
      summary: Obtener lodge por ID
      tags: [Lodges]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Lodge encontrado. }
        '404': { description: Lodge no existe. }
        '500': { description: Error del servidor. }

    put:
      summary: Actualizar lodge por ID
      tags: [Lodges]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [hotel, size, bedroom, bathroom, capacity, season]
              properties:
                hotel: { type: string }
                size: { type: number }
                bedroom: { type: number }
                bathroom: { type: number }
                capacity: { type: number }
                season:
                  type: object
                  required: [high, medium, low]
                  properties:
                    high: { type: number }
                    medium: { type: number }
                    low: { type: number }
      responses:
        '200': { description: Lodge actualizado con éxito. }
        '400': { description: Datos inválidos. }
        '404': { description: Lodge no encontrado. }
        '500': { description: Error del servidor. }

    patch:
      summary: Agregar imagen al lodge
      tags: [Lodges]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [image]
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200': { description: Imagen agregada con éxito. }
        '400': { description: Faltan campos o imagen. }
        '404': { description: Lodge no encontrado. }
        '500': { description: Error del servidor. }

    delete:
      summary: Eliminar lodge por ID
      tags: [Lodges]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Lodge eliminado con éxito. }
        '400': { description: No se puede eliminar, tiene reservas o historial. }
        '404': { description: Lodge o usuario no encontrado. }
        '500': { description: Error del servidor. }

  /api/lodges/image/{id}:
    delete:
      summary: Eliminar todas las imágenes de un lodge
      tags: [Lodges]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Imágenes eliminadas con éxito. }
        '404': { description: Lodge no encontrado. }
        '500': { description: Error del servidor. }

  /api/lodges/available/{id}:
    patch:
      summary: Cambiar disponibilidad de lodge
      tags: [Lodges]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Disponibilidad cambiada con éxito. }
        '400': { description: Falta imagen o ubicación. }
        '404': { description: Lodge no encontrado. }
        '500': { description: Error del servidor. }

  /api/lodges/wifi/{id}:
    patch:
      summary: Cambiar estado del wifi del lodge
      tags: [Lodges]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Wifi cambiado con éxito. }
        '404': { description: Lodge no encontrado. }
        '500': { description: Error del servidor. }

  /api/lodges/location/{id}:
    patch:
      summary: Establecer ubicación en el lodge
      tags: [Lodges]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [mapUrl]
              properties:
                mapUrl:
                  type: string
      responses:
        '200': { description: Ubicación establecida con éxito. }
        '400': { description: Ubicación no válida. }
        '404': { description: Lodge no encontrado. }
        '500': { description: Error del servidor. }

  /api/lodges/{userId}:
    post:
      summary: Crear lodge asociado a un usuario
      tags: [Lodges]
      parameters:
        - in: path
          name: userId
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [hotel, size, bedroom, bathroom, capacity, season]
              properties:
                hotel: { type: string }
                size: { type: number }
                bedroom: { type: number }
                bathroom: { type: number }
                capacity: { type: number }
                season:
                  type: object
                  required: [high, medium, low]
                  properties:
                    high: { type: number }
                    medium: { type: number }
                    low: { type: number }
      responses:
        '201': { description: Lodge creado con éxito. }
        '400': { description: Datos inválidos o límite alcanzado. }
        '404': { description: Usuario no encontrado. }
        '500': { description: Error del servidor. }

  /api/lodges/user/{userId}:
    get:
      summary: Obtener todos los lodges de un usuario
      tags: [Lodges]
      parameters:
        - in: path
          name: userId
          required: true
          schema: { type: string }
      responses:
        '200': { description: Lista de lodges del usuario. }
        '400': { description: El userId no existe. }
        '500': { description: Error del servidor. }

  /api/lodges/delete/all:
    delete:
      summary: Eliminar todos los lodges (solo dev)
      tags: [Lodges]
      responses:
        '200': { description: Todos los lodges eliminados con éxito. }
        '500': { description: Error del servidor. }