openapi: "3.0.3"
info:
  title: "Documentación de la App de Reservas de Cabañas - Cabañas"
  description: "API para la administración y consulta de cabañas disponibles para hospedaje."
  version: "1.0.0"

servers:
  - url: http://localhost:8080

paths:
  /api/lodges:
    get:
      summary: Obtener lodges filtrados
      description: Devuelve una lista paginada de lodges con filtros opcionales.
      tags:
        - Lodges
      parameters:
        - in: query
          name: hotel
          schema: { type: string }
        - in: query
          name: size
          schema: { type: integer }
        - in: query
          name: bedroom
          schema: { type: integer }
        - in: query
          name: bathroom
          schema: { type: integer }
        - in: query
          name: capacity
          schema: { type: integer }
        - in: query
          name: wifi
          schema: { type: string, enum: [true, false] }
        - in: query
          name: available
          schema: { type: string, enum: [true, false] }
        - in: query
          name: high
          schema: { type: number }
        - in: query
          name: medium
          schema: { type: number }
        - in: query
          name: low
          schema: { type: number }
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 10 }
      responses:
        '200':
          description: Lista de lodges.
        '500':
          description: Error del servidor.

    post:
      summary: Crear lodge
      description: Crea una nueva cabaña.
      tags:
        - Lodges
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [hotel, size, bedroom, bathroom, capacity, season]
              properties:
                hotel: { type: string, example: "cabaña el sol" }
                size: { type: number, example: 80 }
                bedroom: { type: number, example: 3 }
                bathroom: { type: number, example: 2 }
                capacity: { type: number, example: 6 }
                season:
                  type: object
                  required: [high, medium, low]
                  properties:
                    high: { type: number, example: 120000 }
                    medium: { type: number, example: 95000 }
                    low: { type: number, example: 75000 }
      responses:
        '201':
          description: Lodge creado con éxito.
        '400':
          description: Datos inválidos.
        '500':
          description: Error del servidor.

    delete:
      summary: Eliminar todos los lodges
      description: Borra todos los registros de cabañas.
      tags:
        - Lodges
      responses:
        '200':
          description: Todos los lodges eliminados.
        '500':
          description: Error del servidor.

  /api/lodges/{id}:
    get:
      summary: Obtener lodge por ID
      tags:
        - Lodges
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Lodge encontrado.
        '404':
          description: Lodge no existe.
        '500':
          description: Error del servidor.

    put:
      summary: Actualizar lodge por ID
      tags:
        - Lodges
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [hotel, size, bedroom, bathroom, capacity, wifi, season]
              properties:
                hotel:
                  type: string
                  default: "cabaña el bosque"
                size:
                  type: number
                  default: 90
                bedroom:
                  type: number
                  default: 3
                bathroom:
                  type: number
                  default: 2
                capacity:
                  type: number
                  default: 6
                wifi:
                  type: boolean
                  default: true
                season:
                  type: object
                  required: [high, medium, low]
                  properties:
                    high:
                      type: number
                      default: 130000
                    medium:
                      type: number
                      default: 100000
                    low:
                      type: number
                      default: 75000
      responses:
        '200':
          description: Lodge actualizado con éxito.
        '400':
          description: Error en los datos.
        '404':
          description: Lodge no existe.
        '500':
          description: Error interno.

    patch:
      summary: Agregar imagen al lodge
      tags:
        - Lodges
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [image]
              properties:
                image:
                  type: string
                  example: "https://url.com/imagen.jpg"
      responses:
        '200':
          description: Imagen agregada.
        '400':
          description: Falta el campo `image`.
        '404':
          description: Lodge no existe.
        '500':
          description: Error interno.

    delete:
      summary: Eliminar lodge por ID
      tags:
        - Lodges
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Lodge eliminado.
        '404':
          description: Lodge no existe.
        '500':
          description: Error del servidor.

  /api/lodges/image/{id}:
    delete:
      summary: Eliminar todas las imágenes de un lodge
      tags:
        - Lodges
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Imágenes eliminadas.
        '404':
          description: Lodge no existe.
        '500':
          description: Error del servidor.

  /api/lodges/available/{id}:
    patch:
      summary: Cambiar estado de disponibilidad
      tags:
        - Lodges
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Disponibilidad cambiada.
        '404':
          description: Lodge no existe.
        '500':
          description: Error del servidor.