openapi: "3.0.3"
info:
  title: "Documentación de la App de Reservas de Cabañas - Cabañas"
  description: "API para la administración y consulta de cabañas disponibles para hospedaje."
  version: "1.0.0"

servers:
  - url: http://localhost:8080

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:

  /api/sessions:
    get:
      summary: "Obtener todas las sesiones"
      description: "Devuelve un listado de todas las sesiones activas en la plataforma."
      tags:
        - Sessions
      responses:
        '200':
          description: "Sesiones obtenidas con éxito."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Todas las Sesiones.."
                  sessions:
                    type: array
                    items:
                      type: object
        '500':
          description: "Error interno del servidor."

  /api/sessions/{userId}:
    get:
      summary: "Obtener sesión por ID de usuario"
      description: "Devuelve la sesión activa correspondiente a un usuario específico."
      tags:
        - Sessions
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: "ID del usuario"
      responses:
        '200':
          description: "Sesión obtenida con éxito."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "sesion obtenida por el id.."
                  session:
                    type: object
        '404':
          description: "Sesión no encontrada."
        '500':
          description: "Error interno del servidor."

  /api/sessions/users/registered:
    get:
      summary: "Obtener cantidad de usuarios registrados"
      tags:
        - Sessions
      responses:
        '200':
          description: "Número de usuarios registrados obtenido exitosamente."
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: integer
                    example: 100
        '500':
          description: "Error interno del servidor."

  /api/sessions/users/logged:
    get:
      summary: "Obtener cantidad de usuarios logueados"
      tags:
        - Sessions
      responses:
        '200':
          description: "Número de usuarios logueados obtenido exitosamente."
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: integer
                    example: 10
        '500':
          description: "Error interno del servidor."

  /api/sessions/register:
    post:
      summary: "Registrar un nuevo usuario"
      tags:
        - Sessions
      requestBody:
        required: true
        description: "Datos requeridos para el registro de usuario."
        content:
          application/json:
            schema:
              type: object
              required:
                - first_name
                - last_name
                - email
                - phone
                - password
                - address
              properties:
                first_name:
                  type: string
                  example: "Juan"
                last_name:
                  type: string
                  example: "Pérez"
                email:
                  type: string
                  format: email
                  example: "juan.perez@example.com"
                phone:
                  type: string
                  example: "+56912345678"
                password:
                  type: string
                  example: "123456"
                address:
                  type: object
                  required:
                    - country
                    - state
                    - city
                    - street
                    - number
                  properties:
                    country:
                      type: string
                      example: "Chile"
                    state:
                      type: string
                      example: "Región Metropolitana"
                    city:
                      type: string
                      example: "Santiago"
                    street:
                      type: string
                      example: "Av. Siempre Viva"
                    number:
                      type: string
                      example: "123"
      responses:
        '201':
          description: "Usuario registrado con éxito."
        '400':
          description: "Solicitud incorrecta, faltan campos o formato inválido."
        '409':
          description: "Email ya registrado o contraseña inválida."
        '500':
          description: "Error interno del servidor."

  /api/sessions/login:
    post:
      summary: "Autenticar usuario (Login)"
      tags:
        - Sessions
      requestBody:
        required: true
        description: "Credenciales del usuario para iniciar sesión."
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "juan.perez@example.com"
                password:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: "Login realizado con éxito."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login realizado con éxito"
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: "Solicitud incorrecta, faltan campos."
        '401':
          description: "Contraseña incorrecta."
        '404':
          description: "Email no registrado."
        '409':
          description: "Usuario ya logeado."
        '500':
          description: "Error interno del servidor."

  /api/sessions/logout:
    post:
      summary: "Cerrar sesión (Logout)"
      tags:
        - Sessions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "Logout realizado con éxito."
        '401':
          description: "Token no encontrado."
        '500':
          description: "Error interno del servidor."